"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import logo from "../../public/Logo.png"
import Link from "next/link";
import { usePathname } from "next/navigation";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "portfolio - MdAliHossen",
    template: "%s | MdAliHossen"
  },
  description: "Generated by create next app",
};
const pathname = usePathname()
 
const navLinks = [ 
  {name: "Home", href: "/"},
  {name: "About", href: "/about"},
  {name: "Lab", href: "/lab"},
] 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex w-full h-[100px] bg-[#1A0B2E]">
          <div className="menubar flex max-w-[1320px] mx-auto justify-content space-x-150 my-auto">

          <div className="logo space-between">
            <Image className="w-[35px] h-[39px]"
             src={logo}
             alt="logo"
             />
          </div>
          
            <div className="menu text-[20px] [&>*+*]:ml-25 plus-jakarta-sans">
            
              {
                navLinks.map((link,key)=>{
                  return(
                    <Link href={link.href} key={key}>
                    {link.name}
                    </Link>
                  )
                })
              }
             </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
