import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import logo from "../../public/Logo.png"
import Link from "next/link";
// import { usePathname } from "next/navigation";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "portfolio - MdAliHossen",
    template: "%s | MdAliHossen"
  },
  icons:{
    icon: "/favicon.ico"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex w-full h-[100px] bg-[#1A0B2E] top-0 fixed mb-50">
          <div className="menubar flex max-w-[1320px] mx-auto justify-content space-x-150 my-auto">

          <div className="logo space-between ml-[-15px]">
            {/* <img src="" alt="" /> */}
            <Image className="w-[35px] h-[39px]"
             src={logo}
             alt="logo"
             
             />
          </div>
          
            <div className="menu text-[20px] [&>*+*]:ml-25 plus-jakarta-sans">
            
              <Link href="/" >Home</Link>
              <Link href="/about" >About</Link>
              <Link href="/contact" >Contact</Link>
          
             </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
